# Create: netlify.toml (in the same directory as package.json)
[build]
  command = "CI=false npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"